### ISSUE TITLE
We need a divider

### ISSUE THREAD

**Issue by antonblanchard** [antonblanchard/microwatt#11]
Right now we implement division in simulation, but not synthesis. We don't need anything spectacular, because modern compilers are quite good at optimising divides away. A basic non pipelined radix 2 divider would do nicely. Even so, I'm sure there are a lot of corner cases to take care of.

There are 4 32 bit and 4 64 bit divide instructions, but best to start with the ones we see in micropython: divd, divdu, divw, and divwu.

**Comment by mikey** [comment]
solved PR #74 via 25b9450475704ae58cddf44438248d3a3bb56f1e

**Comment by antonblanchard** [comment]
Thanks, closing
