### ISSUE TITLE
just to play : using windows wsl/ubuntu , building ghdl and running micropython

### ISSUE THREAD

**Issue by titof49** [antonblanchard/microwatt#111]
its relatively slow but it work using Windows wsl , Ubuntu and building ghdl with llvm  ;-> using your tutorial to test.

![image](https://user-images.githubusercontent.com/26005969/67128960-8b717800-f1fd-11e9-9697-b88211b82b63.png)

   54  sudo apt-get install gcc-4.8-powerpc-linux-gnu g++-4.8-powerpc-linux-gnu binutils-4.8-powerpc-linux-gnu
   55  sudo apt-get install gcc-powerpc64le-linux-gnu
   56  sudo apt-get install g++-powerpc64le-linux-gnu
   57  sudo apt-get install binutils-powerpc64le-linux-gnu
   58  sudo apt-get install binutils-powerpc64le-linux-gnu-dbg
   61  sudo apt-get install binutils-powerpc64le-linux
   64  sudo apt-get install gcc-4.8-powerpc-linux-gnu g++-4.8-powerpc-linux-gnu binutils-4.8-powerpc-linux-gnu

  119  sudo apt-get install llvm
  120  sudo apt-get install llvm-8

and for ghdl

https://gist.github.com/mathieucaroff/73ccbd30638d9b37b7129a7b7b8d7726

with these parameters :

 ./configure --prefix=/usr/local --with-llvm-config=/usr/bin/llvm-config-8

**Comment by eine** [comment]
@titof49, which version of WSL are you using? Is it WSL2? Last time we tried, GHDL would not work on WSL1: ghdl/ghdl#551. Maybe it is because of the backend?

**Comment by mikey** [comment]
I'm closing this as it's not an issue AFAICT.
