### ISSUE TITLE
Dockerfile Please

### ISSUE THREAD

**Issue by Art** [antonblanchard/microwatt#124]
Aloha
Leaping into MMXX Please a Dockerfile ... 

Like ...
https://github.com/marcelwa/fiction/blob/master/Dockerfile

Mahalo

Art

**Comment by eine** [comment]
Hi @Art! What do you expect to use the Dockerfile (or docker images) for? Simulation with open source tools (GHDL)? Simulation with vendor tools (ModelSim/QuestaSim/Vivado)? Synthesis with open source tools (GHDL + Yosys + nextpnr)? Synthesis with mixed open source and non-open source tools (Verific + Yosys + nextpnr)? Synthesis with vendor tools (Vivado)?

**Comment by mikey** [comment]
@Art unless you have more input, I'm going to close this.
