### ISSUE TITLE
refresh bundled MicroPython image

### ISSUE THREAD

**Issue by sharkcz** [antonblanchard/microwatt#135]
IMO it would useful to update the bunded MicroPython image in fpga/firmware.hex. It's smaller (~550kB, at least on my system) and mainly has the restart working when Ctrl+D is pressed.

**Comment by antonblanchard** [comment]
Great idea @sharkcz. I updated to the latest upstream, and verified it runs in 384kB. I changed the default amount of RAM in simulation to 384kB to match.

I've also added all images (elf, bin, hex) in micropython/*
