### ISSUE TITLE
CR logical ops need to be implemented

### ISSUE THREAD

**Issue by antonblanchard** [antonblanchard/microwatt#14]
crand, crandc, creqv, crnand, crnor, cror, crorc, crxor are not implemented. We haven't seen them in gcc compiled code, but they do appear quite a lot in llvm code.

**Comment by tomtor** [comment]
I added some in https://github.com/tomtor/microwatt/tree/CR

**Comment by tomtor** [comment]
See #127

**Comment by antonblanchard** [comment]
Thanks @tomtor, closing this now your patch has gone upstream.
