### ISSUE TITLE
Add tests for PMU events

### ISSUE THREAD

**Issue by mikey** [antonblanchard/microwatt#321]
@paulusmack recently added a PMU but we dont have any tests for events yet. Given the design is moves around I think it's likely these events will bit rot over time hence we should add some tests for these events.

**Comment by iagocaran** [comment]
Where can I find more information about the PMU events? The names are understandable, but I was wondering if you have any references.

**Comment by mikey** [comment]
Fixed by @iagocaran in #380  Woot!
