### ISSUE TITLE
Commit eb20195a breaks building of mw_debug on Fedora

### ISSUE THREAD

**Issue by paulusmack** [antonblanchard/microwatt#351]
Fedora's urjtag-devel package doesn't have a static version of liburjtag, just a dynamic version, so commit eb20195a breaks the build.

**Comment by mikey** [comment]
@mkj ping

**Comment by mkj** [comment]
Ah. Maybe it should default to dynamic and have a separate mw_debug_static target? Or a `STATIC=1` variable?

**Comment by mikey** [comment]
I think either of those would be fine. Thanks @mkj

**Comment by mikey** [comment]
Thanks @mkj
