### ISSUE TITLE
Branch cache aliasing between IR=0 and IR=1

### ISSUE THREAD

**Issue by antonblanchard** [antonblanchard/microwatt#391]
I have a test case where we execute a branch with IR=0, then execute code at the same address with IR=1, which has no branch. The branch is incorrectly taken:

https://github.com/antonblanchard/microwatt/commit/25f93fc17e609509ade1d6a1bcb977fe8a075fb6

**Comment by paulusmack** [comment]
I guess we need to include IR in the tag...
